spring:
  application:
    name: file-service
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_improve?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: flms04
  jackson:
    default-property-inclusion: non_null

file:
  download:
    base-path: "D:/software/dev/test/download/"
  upload:
    base-path: "D:/software/dev/test/upload/"