spring:
  application:
    name: file-service
  datasource:
    url: jdbc:mysql://localhost:3306/file-service?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: flms04
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 1GB

file:
  upload:
    base-path: "D:/software/dev/test/upload/advance"

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.flz.downloadandupload.persist.dataobject
